# Use version 2.1 for Go.
version: 2.1

jobs:
  # Build job for building our Go web application.
  build:
    docker:
      # Choose CircleCI's Golang image.
      - image: cimg/go:1.13
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    
    # Set working directory to /tmp.
    working_directory: /tmp

    # Steps to execute to build our project.
    steps:
      # Checkout our source code.
      - checkout

      # Create build directory.
      - run: mkdir -p build/

      # Install Go Mux dependency.
      - run: go get -u github.com/gorilla/mux

      # Build our Go web application.
      - run: go build -o build/web src/web.go

      # Allow us to use web binary in other jobs (e.g. test).
      - persist_to_workspace:
          root: build/
          paths:
            - web

  # Test our Go web application using the tests/execbtn.py Python script.
  test:
    docker:
      # Choose CircleCI's Golang image.
      - image: cimg/go:1.13
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS

    # Set working directory to /tmp.
    working_directory: /tmp

    # Steps to test our project.
    steps:
      # Attach workspace.
      - attach_workspace:
        at: build
      
      # Test.
      - run: ls -la build/

      - run: echo "This test job is not finished."
# Perform our workflows.
worksflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
        # Require our build job to succeed.
        requires:
          - build
      - hold:
        type: approval
        # Require both our build and test jobs to succeed.
        requires:
          - build
          - test
      - deploy:
        requires:
          - hold