# Use version 2.1 for Go.
version: 2.1

jobs:
  # Build job for building our Go web application.
  build:
    docker:
      # Choose CircleCI's Golang image.
      - image: cimg/go:1.13
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS

    # Steps to execute to build our project.
    steps:
      # Checkout our source code.
      - checkout

      # Create build directory.
      - run: mkdir -p build/

      # Install Go Mux dependency.
      - run: go get -u github.com/gorilla/mux

      # Build our Go web application.
      - run: go build -o build/web src/web.go

      # Allow us to use web binary in other jobs (e.g. test).
      - persist_to_workspace:
          root: build/
          paths:
            - web

  # Test our Go web application using the tests/execbtn.py Python script.
  test:
    docker:
      # Choose CircleCI's Python image.
      - image: circleci/python:3.7.2
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS

    # Steps to test our project.
    steps:
      # Checkout source code.
      - checkout

      # Attach workspace.
      - attach_workspace:
          at: build/

      # Run web application.
      - run:
          name: Go Web Application
          command: ./build/web
          background: true

      # Update.
      - run: sudo apt-get update

      # Install software common properties.
      - run: sudo apt-get install -y software-properties-common

      # Install Firefox.
      - run: sudo apt-get install -y firefox-esr

      # Install the Geckodriver for Firefox.
      - run: wget https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz

      # Extract the file.
      - run: tar -xzvf geckodriver-v0.28.0-linux64.tar.gz

      # Move file to /usr/bin.
      - run: sudo mv geckodriver /usr/bin

      # Install Selenium for Python.
      - run: pip install selenium

      # Run our Python script.
      - run: python tests/execbtn.py -p /usr/lib/firefox/firefox

# Perform our workflows.
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build